language: haskell

env:
 - CABALVER=1.22 GHCVER=7.8.1
 - CABALVER=1.22 GHCVER=7.8.2
 - CABALVER=1.22 GHCVER=7.8.3
 - CABALVER=1.22 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=1.22 GHCVER=7.10.2
 - CABALVER=1.22 GHCVER=7.10.3
 - CABALVER=1.24 GHCVER=8.0.1
 - CABALVER=1.24 GHCVER=8.0.2
 - CABALVER=head GHCVER=head

matrix:
  allow_failures:
   - env: CABALVER=head GHCVER=head

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/home/travis/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal update
 - cabal install cabal-install
 - /home/travis/.cabal/bin/cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - /home/travis/.cabal/bin/cabal install --only-dependencies --enable-tests

script:
 - /home/travis/.cabal/bin/cabal configure --enable-tests
 - /home/travis/.cabal/bin/cabal build --ghc-options=-Werror
 - /home/travis/.cabal/bin/cabal test
 - /home/travis/.cabal/bin/cabal check
 - /home/travis/.cabal/bin/cabal sdist
 - export SRC_TGZ=$(/home/travis/.cabal/bin/cabal info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      /home/travis/.cabal/bin/cabal install --force-reinstalls "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi

notifications:
  email:
    recipients:
      - anselm.scholl@tu-harburg.de
    on_success: change
    on_failure: always
